from os import listdir,makedirs,walk
from os.path import join,basename,exists,abspath,isdir,dirname
from glob import glob
from shutil import copyfile
import pandas as pd

configfile: "config/config.yaml"

#container: 'docker://greydongilmore/dicom2bids-clinical:latest'

subject_id = config['subject_prefix'].upper() + '{subject}'

config['dicom_dir'] = join(config['bids_dir'], 'sourcedata', 'dicoms')
config['out_dir'] = config['bids_dir']
config['clinical_event_file'] = join(config['bids_dir'], 'events.tsv')
config['participants_tsv'] = join(config['bids_dir'], 'participants_run.tsv')

if not exists(join(config['out_dir'], 'logs')):
    makedirs(join(config['out_dir'], 'logs'))

if exists(config['participants_tsv']):
    df = pd.read_table(config['participants_tsv'],dtype=str)
    subjects=df.participant_id.to_list()
    if subjects:
        if isinstance(subjects[0],str):
            subjects = [ s.strip('sub-P') for s in subjects]
        else:
            subjects = [ str(s).zfill(3) for s in subjects]
    else:
        subjects = [x.split('-')[1] for x in listdir(config['dicom_dir']) if isdir(join(config['dicom_dir'], x))]
else:
    subjects = [x.split('-')[1] for x in listdir(config['dicom_dir']) if isdir(join(config['dicom_dir'], x))]

final_outputs = []

include: 'rules/common.smk'

if config['fmriprep']['run']:
    include: 'rules/fmriprep.smk'
    if not exists(join(config['out_dir'], 'derivatives', 'fmriprep')):
       makedirs(join(config['out_dir'], 'derivatives', 'fmriprep'))

include: 'rules/dicom2bids.smk'

if config['fastsurfer']['run']:
    include: 'rules/fastsurfer.smk'

rule all:
	input:
		final_outputs


