from os import listdir,makedirs,walk,path
from glob import glob
from shutil import copyfile
import pandas as pd

configfile: "config/config.yaml"

#container: 'docker://greydongilmore/dicom2bids-clinical:latest'

#if not exists(join(config['out_dir'],'logs')):
#	makedirs(join(config['out_dir'],'logs'))

subject_id = config['subject_prefix'].upper() + '{subject}'

if config['participants_tsv']:
    df = pd.read_table(config['participants_tsv'])
    subjects = [s.strip('sub-') for s in df.participant_id.to_list() ]
else:
    subjects = [x.split('-')[1] for x in listdir(config['dicom_dir']) if path.isdir(path.join(config['dicom_dir'], x))]

rule all:
	input:
		expand(path.join(config['out_dir'], 'logs', 'sub-' + subject_id + "_dicom2bids.done"), subject=subjects)

include: 'rules/dicom2bids.smk'