from os import listdir,makedirs,walk
from os.path import join,isdir,dirname,split,abspath,exists
from glob import glob
from shutil import copyfile

configfile: "config/config.yaml"

#container: 'docker://greydongilmore/dicom2bids-clinical:latest'

if not exists(join(config['out_dir'],'logs')):
	makedirs(join(config['out_dir'],'logs'))

subjects = [x.split('-')[1] for x in listdir(config['dicom_dir']) if isdir(join(config['dicom_dir'], x))]

rule all:
	input:
		expand(join(config['out_dir'], 'logs', 'sub-P' + '{subject}' + "_dicom2bids.done"), subject=subjects)

include: 'rules/dicom2bids.smk'
